version: "3.9"

services:
  # MySQL - Database for Decision Maker
  mysql:
    container_name: ${MYSQL_HOST}
    image: mysql:5.6
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_TCP_PORT=${MYSQL_PORT}
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # App - java for Decision Maker build with maven
  app:
    container_name: ${APP_HOST}
    build: ${APPLICATION_ROOT_FOLDER}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - AES_SECRET_KEY=${AES_SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
      - SYSTEM_DOMAIN=${SYSTEM_DOMAIN}
      - DEFAULT_USER=${DEFAULT_USER}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
    volumes:
      - ${APPLICATION_ROOT_FOLDER}:/usr/src/mymaven
      - ${MAVEN_SETTINGS_FOLDER}:/root/.m2
